#!/bin/bash

setvar GameOptions.LastGame.LevelName           "HW-house.lxl"
setvar GameServer.GameInfo.sMapFile             "HW-house.lxl"
setvar GameServer.GameInfo.sMapName             "[HW] House"

setvar GameOptions.LastGame.ModName             "Crazy Penguins 0.4"
setvar GameServer.GameInfo.sModDir              "Crazy Penguins 0.4"
setvar GameServer.GameInfo.sModName             "Crazy Penguins 0.4"

setvar GameOptions.LastGame.LoadingTime         "100"
setvar GameServer.GameInfo.iLoadingTimes        "100"

setvar GameServer.WeaponRestrictionsFile        ""

setvar GameServer.ServerName "Crazy Penguins dedicated server"

