#!/usr/bin/python -u
# The Python presets are detected from non-Python ones by first line which shouild contain "python" string
# This file contains default settings for all presets, 
# it will be executed before any preset to clean up after previous preset

# TODO: use options.cfg settings as default and don't hardcode any other stuff here

global controlHandler
controlHandler = controlHandlerDefault
cmds.adminCommandHelp_Preset = None
cmds.parseAdminCommand_Preset = None
cmds.userCommandHelp_Preset = None
cmds.parseUserCommand_Preset = None

import random

setvar( "GameOptions.GameInfo.LevelName", cfg.LEVELS[ random.randrange(len(cfg.LEVELS)) ] )

setvar( "GameOptions.GameInfo.ModName", "Classic" )

#  TODO use options.cfg as default
setvar( "GameOptions.GameInfo.LoadingTime", 0 )

setvar( "GameServer.WeaponRestrictionsFile", "" )

setvar("GameOptions.GameInfo.GameType", 0) # 0 - Deathmatch, 1 - TDM, 2 - Tag, 3 - Demolitions, 4 - Hide&Seek

setvar("GameOptions.GameInfo.Lives", cfg.GAME_LIVES)

setvar("GameOptions.GameInfo.KillLimit", cfg.GAME_MAX_KILLS)

setvar("GameOptions.GameInfo.TimeLimit", cfg.GAME_MAX_TIME)

# Other options that controls game
setvar( "GameOptions.GameInfo.GameSpeed", 1) # Beta8+
setvar( "GameOptions.GameInfo.RespawnGroupTeams", 1)
setvar( "GameOptions.GameInfo.AllowConnectDuringGame", 1) # Beta8+

setvar( "GameOptions.GameInfo.Bonuses", 0)
setvar( "GameOptions.GameInfo.BonusNames", 1)
setvar( "GameOptions.GameInfo.BonusFrequency", 30)
setvar( "GameOptions.GameInfo.BonusHealthToWeaponChance", 0.5) # 0 - all healths, 1 - all weapons
setvar( "GameOptions.GameInfo.BonusLife", 60)

setvar( "GameOptions.GameInfo.SuicideDecreasesScore", 1)
setvar( "GameOptions.GameInfo.CountTeamkills", 0)
setvar( "GameOptions.GameInfo.GroupTeamScore", 0)

setvar( "GameOptions.GameInfo.EmptyWeaponsOnRespawn", 0)
setvar( "GameOptions.GameInfo.GroupTeamScore", 0)
setvar( "GameOptions.GameInfo.RespawnTime", 2.5)
setvar( "GameOptions.GameInfo.CountTeamkills", 0)
setvar( "GameOptions.GameInfo.ForceScreenShaking", 1)
setvar( "GameOptions.GameInfo.AllowEmptyGames", 0)

setvar( "GameOptions.GameInfo.SelfHit", 1) # Beta9+
setvar( "GameOptions.GameInfo.SelfInjure", 1) # Beta9+
setvar( "GameOptions.GameInfo.TeamHit", 1) # Beta9+
setvar( "GameOptions.GameInfo.TeamInjure", 1) # Beta9+

setvar( "GameOptions.GameInfo.ForceRandomWeapons", 0) # Beta8+
setvar( "GameOptions.GameInfo.SameWeaponsAsHostWorm", 0) # Beta8+, we should add a bot for that to work

setvar( "GameOptions.GameInfo.RespawnTime", 2.5)
setvar( "GameOptions.GameInfo.ForceScreenShaking", 1)
setvar( "GameOptions.GameInfo.TagLimit", 5)

