#!/usr/bin/python -u
# The Python presets are detected from non-Python ones by first line which shouild contain "python" string
# This file contains default settings for all presets, 
# it will be executed before any preset to clean up after previous preset

global controlHandler, adminCommandHelp_Preset, parseAdminCommand_Preset, userCommandHelp_Preset, parseUserCommand_Preset
controlHandler = controlHandlerDefault
adminCommandHelp_Preset = None
parseAdminCommand_Preset = None
userCommandHelp_Preset = None
parseUserCommand_Preset = None

setvar( "GameOptions.Network.ServerName", cfg.SERVER_NAME )

setvar( "GameOptions.GameInfo.LevelName",   "LieroFactory(Revisited).lxl" )

setvar( "GameOptions.GameInfo.ModName",    "Classic" )

setvar( "GameOptions.GameInfo.LoadingTime", 100 )

setvar( "GameServer.WeaponRestrictionsFile", "cfg/presets/100 LT.wps" )

setvar("GameOptions.GameInfo.GameType", 0) # 0 - Deathmatch, 1 - TDM

setvar("GameOptions.GameInfo.MaxPlayers", cfg.MAX_PLAYERS)

setvar("GameOptions.GameInfo.Lives", cfg.GAME_LIVES)

setvar("GameOptions.GameInfo.KillLimit", cfg.GAME_MAX_KILLS)

setvar("GameOptions.GameInfo.TimeLimit", cfg.GAME_MAX_TIME)

# Options that controls game
setvar("GameOptions.GameInfo.RespawnGroupTeams", 1)
setvar( "GameOptions.GameInfo.AllowConnectDuringGame", 0)
setvar( "GameOptions.GameInfo.ForceRandomWeapons", 0)
setvar( "GameOptions.GameInfo.SameWeaponsAsHostWorm", 0) # We should add a bot for that to work
setvar( "GameOptions.GameInfo.GameSpeed", 1)
setvar( "GameOptions.GameInfo.TagLimit", 5)
setvar( "GameOptions.Network.WelcomeMessage", "<player> from <country> connected - typing go/spamming is useless")
setvar( "GameOptions.GameInfo.Bonuses", 0)
setvar( "GameOptions.GameInfo.BonusNames", 1)
setvar( "GameOptions.GameInfo.BonusFrequency", 30)
setvar( "GameOptions.GameInfo.BonusHealthToWeaponChance", 0.5) # 0 - all healths, 1 - all weapons
setvar( "GameOptions.GameInfo.BonusLife", 60)
setvar( "GameOptions.GameInfo.EmptyWeaponsOnRespawn", 0)
setvar( "GameOptions.GameInfo.GroupTeamScore", 0)
setvar( "GameOptions.GameInfo.RespawnTime", 2.5)
setvar( "GameOptions.GameInfo.SuicideDecreasesScore", 1)
setvar( "GameOptions.GameInfo.CountTeamkills", 0)
setvar( "GameOptions.GameInfo.WeaponSelectionMaxTime", cfg.WEAPON_SELECTION_TIME)
setvar( "GameOptions.GameInfo.ForceScreenShaking", 1)

# General options that should be set
setvar( "GameOptions.Advanced.MaxFPS", 95) # Higher values will decrease netlag, also needed if ServerSideHealth = 1, 
setvar( "GameOptions.GameInfo.AllowStrafing", 1)
setvar( "GameOptions.GameInfo.ServerSideHealth", 0) # Turn this on if ppl hack and don't die on your server
setvar( "GameOptions.Game.AntilagMovementPrediction", 1) # If ServerSideHealth = 1 this influences gameplay
setvar( "GameOptions.Game.Blood", 0)
setvar( "GameOptions.Game.Particles", 0) # Ded server does not need any eye candies
setvar( "GameOptions.Game.Shadows", 0) # Ded server does not need any eye candies
setvar( "GameOptions.GameInfo.AllowNickChange", 0)
setvar( "GameOptions.Network.AllowRemoteBots", 1)
setvar( "GameOptions.Network.AllowWantsJoinMsg", 1)
setvar( "GameOptions.Network.Password", "") # Not used
setvar( "GameOptions.Network.RegisterServer", 1)
setvar( "GameOptions.Network.WantsToJoinFromBanned", 0)
setvar( "GameOptions.Network.WelcomeMessage", cfg.WELCOME_MESSAGE)
setvar( "GameOptions.Misc.LogConversations", 1)
setvar( "GameOptions.Advanced.MatchLogging", 0) # Do not save game results screenshot
setvar( "GameOptions.Misc.ScreenshotFormat", 1) # 0 = JPG, 1 = PNG
setvar( "GameOptions.Network.AutoSetupHttpProxy", 1)
setvar( "GameOptions.Network.EnableChat", 0) # No IRC chat needed for ded server
setvar( "GameOptions.Network.HttpProxy", "")
setvar( "GameOptions.Network.UseIpToCountry", 1) # Needed for correct server messages
setvar( "GameOptions.Network.MaxUploadBandwidth", 60000) # Disable bandwidth limits
setvar( "GameOptions.Network.Speed", 2) # 0 = Modem, 1 = ADSL, 2 = LAN
setvar( "GameServer.bStartDedicated", 0) # This is for auto-start game from GUI, disable this, it will break the scripts
