#!/usr/bin/python -u

setvar( "GameOptions.GameInfo.ModName", "MW 1.0" )

setvar( "GameOptions.GameInfo.LoadingTime", "100" )

setvar( "GameServer.WeaponRestrictionsFile", "cfg/presets/MW 1.0/Standard 100lt.wps" )
