#!/usr/bin/python -u

setvar( "GameOptions.GameInfo.LevelName", "CastleStrike.lxl" )

setvar( "GameOptions.GameInfo.ModName", "MW 1.0" )

setvar( "GameOptions.GameInfo.LoadingTime", "20" )

setvar( "GameServer.WeaponRestrictionsFile", "cfg/presets/Mortar Only.wps" )
