#!/usr/bin/python -u

import random

global worms, io, controlHandler, wormDiedHandler, newWormHandler, gameStartedHandler, wormSpawnedHandler

setvar( "GameOptions.GameInfo.ModName", "Classic" )

setvar( "GameOptions.GameInfo.LoadingTime", "100" )

SetWeaponBans("Bonus only")

weaponChoices = [
	[
		"Spikeballs", "Larpa", "Doomsday", "Cannon", "Napalm", "Super Shotgun", "Chaingun", "Handgun", "Rifle", "Laser",
	],
	[
		"Bazooka", "Bouncy Larpa", "Bouncy Mine", "Explosives", "Flamer", "Gauss Gun", "Minigun", "Mini Rockets", "Winchester", "Zimm",
	],
	[
		"Blaster", "Booby Trap", "Crackler", "Dart", "Float Mine", "Hellraider", "Mine", "RB Rampage", "Shotgun", "Uzi",
	],
	[
		"Big Nuke", "Chiquita Bomb", "Cluster bomb", "Grasshopper", "Grenade", "Mini Nuke",
	],
]

weaponList = []
for i in range(len(weaponChoices)):
	weaponList.extend(random.sample(weaponChoices[i], 5))

for wormid in worms.keys():
	io.privateMsg(wormid, "New guns: " + ", ".join(weaponList))

def gameStartedNewGun():
	global worms, weaponList, io
	for wormid in worms.keys():
		worms[wormid].newgunCount = 0
		io.privateMsg(wormid, "New guns: " + ", ".join(weaponList))
		#weapon = weaponList[0]
		#io.setWormWeapons(wormid, weapon, weapon, weapon, weapon, weapon)

def newWormNewGun(wormid, name):
	global worms, weaponList, io
	worms[wormid].newgunCount = 5 # Penalty for joining mid-game
	weapon = weaponList[5]
	io.privateMsg(wormid, "New guns: " + ", ".join(weaponList[5:]))

def wormSpawnedNewGun(wormid):
	global worms, weaponList, io
	weapon = weaponList[-1]
	if len(weaponList) > worms[wormid].newgunCount:
		weapon = weaponList[worms[wormid].newgunCount]
	io.setWormWeapons(wormid, weapon, weapon, weapon, weapon, weapon)

def wormDiedNewGun(died, killer):
	global worms, weaponList, io
	worms[killer].newgunCount += 1
	weapon = weaponList[-1]
	if len(weaponList) > worms[killer].newgunCount:
		weapon = weaponList[worms[killer].newgunCount]
	io.setWormWeapons(killer, weapon, weapon, weapon, weapon, weapon)
	#io.privateMsg(killer, "New gun: " + weapon)

gameStartedHandler = gameStartedNewGun
newWormHandler = newWormNewGun
wormDiedHandler = wormDiedNewGun
wormSpawnedHandler = wormSpawnedNewGun

