#!/usr/bin/python -u

setvar( "GameOptions.GameInfo.ModName", "Powerstruck - Dawn" )

setvar( "GameOptions.GameInfo.LoadingTime", "100" )

setvar( "GameServer.WeaponRestrictionsFile", "cfg/presets/Standard Powerstruck - Dawn 100lt.wps" )
