#!/usr/bin/python -u

setvar( "GameOptions.GameInfo.ModName", "Classic" )

setvar( "GameOptions.GameInfo.LoadingTime", "20" )

setvar( "GameServer.WeaponRestrictionsFile", "cfg/presets/Rifle only.wps" )


