#!/usr/bin/python -u

setvar( "GameOptions.GameInfo.ModName", "Shock v1.40 Air" )

setvar( "GameOptions.GameInfo.LoadingTime", "100" )

setvar( "GameServer.WeaponRestrictionsFile", "cfg/presets/Shock v1.40 Air/Standard 100lt.wps" )
