#!/usr/bin/python -u

import random
global worms, io

setvar( "GameOptions.GameInfo.ModName", random.choice(["MSF II", "Classic", "WH40K 0.13"]) )
SetWeaponBans()

setvar( "GameOptions.GameInfo.LoadingTime", "100" )

setvar("GameOptions.GameInfo.GameType", 1)

setvar( "GameOptions.GameInfo.FillWithBotsTo", 4 )

for w in worms.values():
	io.setWormTeam( w.iID, 0 )
for f in range(int(len(worms)/2)):
	red = random.choice(worms.values()).iID
	if io.getWormTeam( red ) == 1: # Not "while" to avoid infinite loop
		red = random.choice(worms.values()).iID
	io.setWormTeam( red, 1 )
