#!/usr/bin/python -u
# The Python presets are detected from non-Python ones by first line which shouild contain "python" string

import random

# Edit this list as you like

levels = [	"FossilFacility.lxl",
			"LieroFactory(Revisited).lxl",
			"JailBreak.lxl",
			"Ore Quarry.lxl",
			"RIP_Home.lxl",
			"Sunrise_Mansion.lxl"
		]

setvar( "GameOptions.GameInfo.LevelName", levels[ random.randrange(len(levels)) ] )

setvar( "GameOptions.GameInfo.ModName", "Classic" )

setvar( "GameOptions.GameInfo.LoadingTime", 100 )

setvar( "GameServer.WeaponRestrictionsFile", "cfg/presets/100 LT.wps" )

setvar("GameOptions.GameInfo.GameType", 1) # Team deathmatch, required for this gamemode

setvar("GameOptions.GameInfo.Lives", 0) # Required for this gamemode

setvar("GameOptions.GameInfo.RespawnGroupTeams", 1) # Required for this gamemode

setvar("GameOptions.GameInfo.CountTeamkills", 0)

def controlHandlerTeamArena():

	RoundsToWin = 5 # You may change this var
	WaitInLobbyBeforeNextRound = cfg.WAIT_BEFORE_GAME # You may change this var, it can be zero

	global worms, gameState, lobbyChangePresetTimeout, lobbyWaitBeforeGame, lobbyWaitAfterGame, lobbyWaitGeneral, lobbyEnoughPlayers, oldGameState, sentStartGame
	global TeamArenaScore, TeamArenaRound
	try:
		temp = TeamArenaScore
	except NameError:
		TeamArenaScore = [0,0,0,0]
	try:
		temp = TeamArenaRound
	except NameError:
		TeamArenaRound = -1
	
	if gameState == GAME_LOBBY:

		# Do not check ping in lobby - it's wrong
		# End round if some team reaches max score or if only 1 worm left
		for i in range(4):
			if TeamArenaScore[i] >= RoundsToWin or ( TeamArenaRound >= 0 and len(worms) <= 1 ):
				msg = "Final score: blue %i red %i" % ( TeamArenaScore[0], TeamArenaScore[1] )
				if cfg.MAX_TEAMS >= 3:
					msg += " green %i" % TeamArenaScore[2]
				if cfg.MAX_TEAMS >= 4:
					msg += " yellow %i" % TeamArenaScore[3]
				io.chatMsg(msg)
				TeamArenaRound = -1
				TeamArenaScore = [0,0,0,0]

		if TeamArenaRound >= 0:

			msg = "Round %i: blue %i red %i" % ( TeamArenaRound, TeamArenaScore[0], TeamArenaScore[1] )
			if cfg.MAX_TEAMS >= 3:
				msg += " green %i" % TeamArenaScore[2]
			if cfg.MAX_TEAMS >= 4:
				msg += " yellow %i" % TeamArenaScore[3]

			if lobbyWaitBeforeGame == WaitInLobbyBeforeNextRound:
				io.chatMsg(msg)
			lobbyWaitBeforeGame -= 1

			if lobbyWaitBeforeGame <= 0 and len(worms) >= cfg.MIN_PLAYERS:
				if not sentStartGame:
					for i in worms.keys():
						if worms[i].iID == -1:
							continue
						worms[i].Lives = 0
					io.startGame()
					io.chatMsg(msg)

		else:
		
			lobbyChangePresetTimeout -= 1
    
			if oldGameState != GAME_LOBBY or lobbyChangePresetTimeout <= 0:
				lobbyChangePresetTimeout = cfg.PRESET_TIMEOUT
				selectNextPreset()
				lobbyEnoughPlayers = False # reset the state
				lobbyWaitGeneral = cfg.WAIT_BEFORE_SPAMMING_TOO_FEW_PLAYERS_MESSAGE
				lobbyWaitAfterGame = 0
				if oldGameState == GAME_PLAYING:
					lobbyWaitAfterGame = cfg.WAIT_AFTER_GAME
    
			lobbyWaitAfterGame -= 1
    
			if lobbyWaitAfterGame <= 0:
    
				lobbyWaitGeneral -= 1
    
				if not lobbyEnoughPlayers and lobbyWaitGeneral <= 0:
					lobbyWaitGeneral = cfg.WAIT_BEFORE_SPAMMING_TOO_FEW_PLAYERS_MESSAGE
					io.chatMsg(cfg.TOO_FEW_PLAYERS_MESSAGE)
    
				if not lobbyEnoughPlayers and len(worms) >= cfg.MIN_PLAYERS: # Enough players already - start game
					lobbyEnoughPlayers = True
					io.chatMsg(cfg.WAIT_BEFORE_GAME_MESSAGE)
					lobbyWaitBeforeGame = cfg.WAIT_BEFORE_GAME
    
				if lobbyEnoughPlayers and len(worms) < cfg.MIN_PLAYERS: # Some players left when game not yet started
					lobbyEnoughPlayers = False
					io.chatMsg(cfg.TOO_FEW_PLAYERS_MESSAGE)
    
				if lobbyEnoughPlayers and not sentStartGame:
					lobbyWaitBeforeGame -= 1
					if lobbyWaitBeforeGame <= 0: # Start the game
    
						if not cfg.ALLOW_TEAM_CHANGE:
							counter = 0
							for w in worms.values():
								if w.iID != -1:
									io.setWormTeam( w.iID, counter % cfg.MAX_TEAMS )
									counter += 1
						
						for i in worms.keys():
							if worms[i].iID == -1:
								continue
							worms[i].Lives = 0
						
						TeamArenaRound = 0
						TeamArenaScore = [0,0,0,0]
						io.startGame()
						if cfg.ALLOW_TEAM_CHANGE:
							io.chatMsg(cfg.TEAM_CHANGE_MESSAGE)

	if gameState == GAME_WEAPONS:
	
		if len(worms) < cfg.MIN_PLAYERS: # Some players left when game not yet started
			io.gotoLobby()

	if gameState == GAME_PLAYING:

		checkMaxPing()

		teamAlive = [0,0,0,0]
		for i in worms.keys():
			if worms[i].iID == -1:
				continue
			if worms[i].Lives >= 0:
				teamAlive[worms[i].Team] += 1

		teamAliveCount = 0
		teamAliveIdx = -1
		for i in range(4):
			if teamAlive[i] > 0:
				teamAliveCount += 1
				teamAliveIdx = i
		if teamAliveCount == 1:
			TeamArenaRound += 1
			TeamArenaScore[teamAliveIdx] += 1
			lobbyWaitBeforeGame = WaitInLobbyBeforeNextRound
			io.gotoLobby()
		if teamAliveCount == 0:
			lobbyWaitBeforeGame = WaitInLobbyBeforeNextRound
			io.gotoLobby()
			
def adminCommandHelpTeamArena(wormid):
	io.privateMsg(wormid, "%sreset - resets TeamArena state" % cfg.ADMIN_PREFIX)

def parseAdminCommandTeamArena(wormid, cmd, params):
	global TeamArenaScore, TeamArenaRound
	try:
		temp = TeamArenaScore
		temp = TeamArenaRound
	except NameError:
		return False

	if cmd == "reset":
		io.gotoLobby()
		msg = "Final score: blue %i red %i" % ( TeamArenaScore[0], TeamArenaScore[1] )
		if cfg.MAX_TEAMS >= 3:
			msg += " green %i" % TeamArenaScore[2]
		if cfg.MAX_TEAMS >= 4:
			msg += " yellow %i" % TeamArenaScore[3]
		time.sleep(1)
		io.chatMsg(msg)
		TeamArenaRound = -1
		TeamArenaScore = [0,0,0,0]
		
		return True
	
	return False


def userCommandHelpTeamArena(wormid):
	io.privateMsg(wormid, "%sscore - prints TeamArena score" % cfg.USER_PREFIX)

def parseUserCommandTeamArena(wormid, cmd, params):
	global TeamArenaScore, TeamArenaRound
	try:
		temp = TeamArenaScore
		temp = TeamArenaRound
	except NameError:
		return False

	if cmd == "score":
		msg = "Round %i: blue %i red %i" % ( TeamArenaRound, TeamArenaScore[0], TeamArenaScore[1] )
		if cfg.MAX_TEAMS >= 3:
			msg += " green %i" % TeamArenaScore[2]
		if cfg.MAX_TEAMS >= 4:
			msg += " yellow %i" % TeamArenaScore[3]
		io.privateMsg(wormid, msg)
		
		return True
	
	return False

global controlHandler
controlHandler = controlHandlerTeamArena
cmds.adminCommandHelp_Preset = adminCommandHelpTeamArena
cmds.parseAdminCommand_Preset = parseAdminCommandTeamArena
cmds.userCommandHelp_Preset = userCommandHelpTeamArena
cmds.parseUserCommand_Preset = parseUserCommandTeamArena

if cfg.ALLOW_TEAM_CHANGE:
	io.chatMsg(cfg.TEAM_CHANGE_MESSAGE)
