#!/bin/bash

IFS='
'

CURDIR="`pwd`/`dirname $0`"

function startlobby() {
	echo "startlobby"
}

function startgame() {
	echo "startgame"
}

function msg() {
	echo "msg $1"
}

function chatmsg() {
	echo "chatmsg $1"
}

function setvar() {
	echo "setvar $1 $2"
}

function sendlobbyupdate() {
	echo "sendlobbyupdate"
}

function start_with_countdown() {
	c=10
	while [ "$c" -ge 1 ]; do
		[ "$c" -ge 10 ] && d=2 || d=1
		msg "$c ..."
		chatmsg "$c ..."
		sleep $d
		c=$(expr "$c" - $d)
	done

	startgame
	wait_for_gameend
}

function wait_for_gameend() {
	local signal
	while read signal; do
		msg "gameloop: $signal"
		[ "$signal" == "backtolobby" ] && {
			sleep 1
			chatmsg "back in lobby, waiting ..."
			return
		}
		[ "$signal" == "quit" ] && exit
	done
}

function signal_handler() {
	local signal
	while read signal; do
		msg "lobby: $signal"
		[ "$signal" == "quit" ] && exit
	done
}

preset=0

function select_next_preset() {
	p=0
	for f in $CURDIR/presets/* ; do
		if [ $p == $preset ] ; then
			msg "Preset `basename $f`"
			chatmsg "Preset `basename $f`"
			. "$f"
		fi
		p=`expr $p '+' 1`
	done
	preset=`expr $preset '+' 1`
	if [ $preset -ge $p ]; then
		preset=0
	fi
	sendlobbyupdate
}

echo "getcomputerwormlist"

startlobby

while true; do
	select_next_preset
	start_with_countdown
done

