#!/usr/bin/python -u

# Dedicated Control handler script for OpenLieroX
# (http://openlierox.sourceforge.net)

# We're expecting this file to be run from "scripts" dir - that's from rev. 3260 or so
# TODO: NO, we are not expecting this!
# It was only done because this script is buggy and does not work otherwise.

import os, sys, time

# Add current dir to module search path
sys.path.append( os.getcwd() )
sys.path.append( os.path.dirname(sys.argv[0]) )

import dedicated_control_io as io # control handler

# Add dir with config file to module search path
try:
	sys.path.append(os.path.dirname(io.getFullFileName("cfg/dedicated_config.py")))
except:
	pass

import dedicated_config as cfg # Per-host config
import dedicated_control_handler as hnd # control handler

## The game loop ##

hnd.init()

io.messageLog("Dedicated_control started",io.LOG_INFO)

def MainLoop():
	hnd.signalHandler(io.getSignal())


if not io.OlxImported:
	while hnd.gameState != hnd.GAME_QUIT:
		MainLoop()
	
	io.messageLog("Dedicated_control stopped",io.LOG_INFO)
