CC= g++
OBJECTS= \
button.o \
context.o \
list.o \
wnd.o \
xml.o \

CFLAGS= -O3
LIBRARY= libomfggui.a

$(LIBRARY): $(OBJECTS)
	ar rs $@ $^

.cpp.o:
	$(CC) -c $< $(CFLAGS) $(DEFINES)

clean:
	rm $(OBJECTS)
