Document: openlierox
Title: Debian openlierox Manual
Author: <insert document author here>
Abstract: This manual describes what openlierox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openlierox/openlierox.sgml.gz

Format: postscript
Files: /usr/share/doc/openlierox/openlierox.ps.gz

Format: text
Files: /usr/share/doc/openlierox/openlierox.text.gz

Format: HTML
Index: /usr/share/doc/openlierox/html/index.html
Files: /usr/share/doc/openlierox/html/*.html

  
