To compile, you'll need:
 - libopenal
 - libalut
 - libvorbisfile
 - liballegro4.2.0
 - libzoidcom
 - libboost filesystem
 - libboost signals
 - zlib
 - libpng
 - scons
 - a C++ compiler

In Windows, the scons build will use the MinGW toolset - MSVC++ isn't supported