#!/bin/sh
# Start/stop OpenLieroX dedicated server

### BEGIN INIT INFO
# Provides:             OpenLieroX
# Required-Start:       $local_fs $time $network $named
# Required-Stop:        $local_fs $time $network $named
# Should-Start:         
# Should-Stop:          
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    OpenLieroX dedicated server
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/bin
export PATH # OLX will run Python as child process, so we may need to export this
DAEMON=/usr/games/openlierox -dedicated
DATADIR=/usr/share/games/openlierox # OLX should run from this dir - it will execute "`pwd`/scripts/dedicated_control" file from there
PIDFILE=/var/run/openlierox.pid
LOGFILE=/var/log/openlierox.log

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_begin_msg "Starting OpenLieroX dedicated server"
	start-stop-daemon --start --quiet -b -m -p $PIDFILE -d $DATADIR --exec $DAEMON < /dev/null > $LOGFILE 2>&1 
	log_end_msg $?
    ;;
  stop)
	log_begin_msg "Stopping OpenLieroX dedicated server"
	start-stop-daemon --stop --quiet -m -p $PIDFILE
	log_end_msg $?
    ;;
  #reload)
    #
    # If the daemon can reload its config files on the fly
    # for example by sending it SIGHUP, do it here.
    #
    # If the daemon responds to changes in its config file
    # directly anyway, make this a do-nothing entry.
    #
    # start-stop-daemon --stop --signal 1 --verbose --exec $DAEMON
    # ;;
  restart|force-reload)
  #
  # If the "reload" option is implemented, move the "force-reload"
  # option to the "reload" entry above. If not, "force-reload" is
  # just the same as "restart".
  #
    log_begin_msg "Restarting OpenLieroX dedicated server"
    start-stop-daemon --stop --quiet -m -p $PIDFILE
    sleep 1
    start-stop-daemon --start --quiet -b -m -p $PIDFILE -d $DATADIR --exec $DAEMON  < /dev/null > $LOGFILE 2>&1
    log_end_msg $?
    ;;
  *)
    echo "Usage: /etc/init.d/openlierox {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
